apiVersion: page.kubepage.dev/v1alpha1
kind: Configuration
metadata:
  labels:
    app.kubernetes.io/name: kubepage-operator
    app.kubernetes.io/managed-by: kustomize
  name: configuration-sample
spec:
  # TODO(user): Add fields here
