apiVersion: page.kubepage.dev/v1alpha1
kind: ServiceEntry
metadata:
  labels:
    app.kubernetes.io/name: kubepage-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceentry-sample
spec:
  instanceRef:
    name: instance-sample
  group: Media
  name: Plex
  href: http://plex.example.com
  icon: plex.png
  description: Media server
  widgets:
    - type: plex
      url: http://plex.example.com
      secrets:
        token:
          secretKeyRef:
            name: plex-credentials
            key: token
