apiVersion: page.kubepage.dev/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: kubepage-operator
    app.kubernetes.io/managed-by: kustomize
  name: instance-sample
spec:
  size: 1
  containerPort: 3000
  allowedHosts: instance-sample.default.svc.cluster.local
